"use client";

import { useState } from "react";
import Image from "next/image";
import { Github, ArrowUpRight, ChevronLeft, ChevronRight } from "lucide-react";

const projetos = [
  {
    titulo: "LiDAR Capture on iOS",
    subtitulo: "Final-Year Project",
    descricao:
      "iOS application for capturing three-dimensional data with the iPhone's LiDAR sensor, together with a Python analysis pipeline that characterises the sensor's accuracy as a function of distance. This work led to two scientific papers submitted to international conferences.",
    tecnologias: ["Swift", "SwiftUI", "ARKit", "Python", "NumPy", "SciPy"],
    imagem: "/projetolidar.PNG",
    github: "https://github.com/RubenSilva13/LiDAR-capture-ios",
    demo: "",
  },
  {
    titulo: "FastAPI Auth — Frontend",
    subtitulo: "Web Application",
    descricao:
      "Web interface in React for an authentication and task management application. Includes user registration and login, with JWT token authentication and communication with a REST API.",
    tecnologias: ["React", "Tailwind CSS", "JavaScript", "JWT"],
    imagem: "/projeto.frontend.png",
    github: "https://github.com/RubenSilva13/FastApi-Auth-React",
    demo: "",
  },
  {
    titulo: "FastAPI Auth — Backend",
    subtitulo: "REST API",
    descricao:
      "REST API built with FastAPI and MySQL, with JWT authentication and task management. It provides the endpoints consumed by the frontend application, with automatic documentation generated by FastAPI.",
    tecnologias: ["FastAPI", "Python", "MySQL", "JWT"],
    imagem: "/projetobackend.png",
    github: "https://github.com/RubenSilva13/FastApi-Auth-Rest",
    demo: "",
  },
];

export default function ProjetosCarrossel() {
  const [atual, setAtual] = useState(0);

  const projeto = projetos[atual];

  const anterior = () => {
    setAtual((i) => (i === 0 ? projetos.length - 1 : i - 1));
  };

  const seguinte = () => {
    setAtual((i) => (i === projetos.length - 1 ? 0 : i + 1));
  };

  return (
    <div className="grid gap-10 md:grid-cols-2 items-center">
      {/* Left side: text */}
      <div className="space-y-6 order-2 md:order-1">
        <span className="block text-6xl md:text-7xl font-bold text-muted-foreground/40">
          0{atual + 1}
        </span>

        <div>
          <h3 className="text-3xl font-bold">{projeto.titulo}</h3>
          <p className="text-xl text-primary">{projeto.subtitulo}</p>
        </div>

        <p className="text-muted-foreground leading-relaxed">
          {projeto.descricao}
        </p>

        <div className="flex flex-wrap gap-2">
          {projeto.tecnologias.map((tec) => (
            <span key={tec} className="text-sm text-primary">
              {tec}
            </span>
          ))}
        </div>

        <div className="flex items-center gap-4 pt-2">
          <a
            href={projeto.github}
            target="_blank"
            rel="noopener noreferrer"
            className="rounded-full border p-3 hover:bg-secondary transition-colors"
            aria-label="View on GitHub"
          >
            <Github className="h-5 w-5" />
          </a>
          {projeto.demo && (
            <a
              href={projeto.demo}
              target="_blank"
              rel="noopener noreferrer"
              className="rounded-full border p-3 hover:bg-secondary transition-colors"
              aria-label="View demo"
            >
              <ArrowUpRight className="h-5 w-5" />
            </a>
          )}
        </div>
      </div>

      {/* Right side: image + arrows */}
      <div className="space-y-4 order-1 md:order-2">
        <div className="relative aspect-video w-full rounded-xl overflow-hidden border bg-secondary p-4">
          <Image
            src={projeto.imagem}
            alt={projeto.titulo}
            fill
            className="object-contain"
          />
        </div>

        <div className="flex justify-end gap-3">
          <button
            onClick={anterior}
            className="rounded-full bg-primary p-3 text-primary-foreground hover:opacity-90 transition-opacity"
            aria-label="Previous project"
          >
            <ChevronLeft className="h-5 w-5" />
          </button>
          <button
            onClick={seguinte}
            className="rounded-full bg-primary p-3 text-primary-foreground hover:opacity-90 transition-opacity"
            aria-label="Next project"
          >
            <ChevronRight className="h-5 w-5" />
          </button>
        </div>
      </div>
    </div>
  );
}
